Issues9
sayanok/zetter pull request #15
Opened 2022-05-30 07:12 UTC by sayanok

2022-05-31 08:37 UTC, sayanok reviewed
めも

2022-05-31 08:37 UTC, sayanok commented on api/controllers/zetter.js
> +    user.introduction = req.body.introduction;
ここ、例えば
```
const userName = req.body.userName;
const introduction = req.body.introduction;

const {userName,  introduction} = newUser;
users.splice(user);
users.push(newUser)+
```
みたいな方がスマート？
でも、結局
```
const userName = req.body.userName;
const introduction = req.body.introduction;
```
を書いてるから、まだ今の方法の方がマシ？

2022-05-31 08:37 UTC, sayanok commented on front/src/components/SettingsProfile.js
> +    }
このメソッドもProfileコンポーネントとまとめたい感ある

2022-06-09 15:03 UTC, sayanok commented on api/controllers/zetter.js
> +    // もっとスマートにかけそう
ここ、例えば
```
const userName = req.body.userName;
const introduction = req.body.introduction;

const {userName,  introduction} = newUser;
users.splice(user);
users.push(newUser);
```
みたいな方がスマート？
でも、結局
```
const userName = req.body.userName;
const introduction = req.body.introduction;
```
を書いてるから、まだ今の方法の方がマシ？

2022-06-09 15:03 UTC, sayanok commented on front/src/components/SettingsProfile.js
> +    const [email, setEmail] = useState('');
この変数をSettingsProfileコンポーネントで持つのが適切かまよっている
理由は、Profileコンポーネントと似たような変数だから
ただし、ProfileコンポーネントもSettingsProfileコンポーネントも他のコンポーネントと親子になっていないのでどこにまとめるべきかわからなくなっている

2022-06-09 15:03 UTC, sayanok commented on front/src/components/SettingsProfile.js
> +    }
このメソッドもProfileコンポーネントとまとめたい感ある

2022-06-09 15:37 UTC, sayanok commented on front/src/components/SettingsProfile.js
> +                        : () => setErrorMessageForUsername('')
いけてないなぁと思ってるけど、やりたい挙動は満たせてるってかんじ
canSubmitメソッド内でsetErrorMessageメソッドを実行するのが読みやすい感じするけど、そうすると`Too many re-renders.`になるのでこうしている
良い方法があれば知りたい

2022-06-11 00:13 UTC, bigen1925 requested changes

2022-06-11 00:13 UTC, bigen1925 commented on api/controllers/zetter.js
> +    res.json(user);
```suggestion
    res.json(req.user);
```
ミドルウェアですでにデータベースから詳細なユーザー情報を取得しているので、再取得する必要はないよ

2022-06-11 00:13 UTC, bigen1925 commented on api/controllers/zetter.js
> +    // もっとスマートにかけそう
うーん、今の書き方が一番読みやすいかなー

別な書き方だと
```suggestion
    index = users.findIndex(user => user.username === req.user.username)
    
    users[index] = {
        ...users[index],
        username: req.body.username,
        introduction: req.body.introduction,
        email: req.body.email,
    }
```

みたいな書き方はできるけど、あんまり読みやすくはないかな〜

2022-06-11 00:13 UTC, bigen1925 commented on api/routes/zetter.js
> +router.put('/update/profile', auth, updateProfile);
```suggestion
router.put('/profile', auth, updateProfile);
```
または
```suggestion
router.patch('/profile', auth, updateProfile);
```
とする

RESTfulとよばれるAPIエンドポイントの設計思想では、

- URLは「リソース」を表現し、できるだけ「操作」を表現しないようにする
- 「操作」は、メソッドやヘッダーを使って表現する

というのが原則で、今回でいうと「profileを(=リソース)」「updateしたい(=操作)」の操作の部分は`PUT`または`PATCH`メソッドを使うことで表現する

2022-06-11 00:13 UTC, bigen1925 commented on api/routes/zetter.js
> +router.put('/update/profile', auth, updateProfile);
参考
https://qiita.com/NagaokaKenichi/items/6298eb8960570c7ad2e9

2022-06-11 00:13 UTC, bigen1925 commented on front/src/components/SettingsProfile.js
> +    const [email, setEmail] = useState('');
このstateはSettingsProfileコンポーネントで「持たなければいけない」かな

複数のコンポーネントで同じstateを持つということは、片方のコンポーネントでstateが更新されたら、もう片方のコンポーネントでもstateが更新される、ということになる

たんに「SettingsProfileでプロファイルの更新ボタンを押したときにその内容がProfileコンポーネントに同期される」というだけであれば嬉しいことなんやけど、stateを共有してしまうとそれだけではすまなくて、例えばSettingsProfileコンポーネントで「内容を入力中だけど、まだsubmitしていない」状態でもstateは同期されてしまう

つまり、SettingsProfileでプロファイルの入力フォームで事項紹介文を「あああいいい」って入力して、更新ボタンをおさずにProfile画面を開くと「あああいいい」になってしまっているということ
これはおそらく意図していない動作だと思う

少し抽象化して考えると、複数のコンポーネントで「いつ何時も常に同じ値が表示されていてほしい」という場合には[stateのリフトアップ](https://ja.reactjs.org/docs/lifting-state-up.html)を行って同じstateを使うのが良いが、少しでも表示内容が違う瞬間があるのであれば別の
stateとして定義する必要がある、ということ

2022-06-11 00:13 UTC, bigen1925 commented on front/src/components/SettingsProfile.js
> +    const [email, setEmail] = useState('');
ちなみにもしstateのリフトアップをする場合の親子関係について考えておくと、今のコンポーネント構成では親子関係は

```
Appコンポーネント
  |-- Profileコンポーネント  
  |-- SettingsProfileコンポーネント
```

になっているので、ProfileとSettingsProfileでstateを共有したい場合には、Appにstateを定義して、ProfileとSettingsProfileにそれぞれpropsとして渡すことになる

2022-06-11 00:13 UTC, bigen1925 commented on front/src/components/SettingsProfile.js
> +    }
単に関数だけを切り出す場合にはReactコンポーネントを使う必要はない

例えば
`src/utils/api.js`
というファイルを新しく作って、下記のようにAPI呼び出しを共通化しておくのがおすすめ
```js
// src/utils/api.js

function callApi(url, config) {
        const authorization = token.value;
        const navigate = useNavigate();
        
        // 'authorization' キーがない場合は先に作っておく
        if(!config.authorization) {
            config.headers = {}
        }
        // Authorizationヘッダに追加
        config.headers.Authorization = authorization

        if (authorization) {
            return fetch(url, config)
                .then((response) => response.json());
        } else {
            console.log('ログインしてください');
            navigate('/login');
        }
}

export callApi;
```

呼び出し側は例えばこうなる
```js
// src/components/SettingsProfile.js
import { callApi } from '../utils/api'

export function SettingsProfile() {
    ....

    function getProfile() {
        callApi('http://localhost:5000/api/zetter/profile').then(data => {
                    setUsername(data.username);
                    setIntroduction(data.introduction);
                    setEmail(data.email);
        })
    }
    
}
```

2022-06-11 00:13 UTC, bigen1925 commented on front/src/components/SettingsProfile.js
> +            <br />
https://mui.com/material-ui/react-text-field/#validation

muiの機能を使うと簡単にもうちょいかっこよくできそう
例えば
```tsx
            <TextField
                ...
                error = {errorMessageForUsername ? true : false}
                helperText = {errorMessageForUsername}
             />
```
のように書く

2022-06-11 00:13 UTC, bigen1925 commented on front/src/components/SettingsProfile.js
> +                        : () => setErrorMessageForUsername('')
どちらかというとonChangeに書くのが良いかな

```suggestion
                onChange={(e) => {
                    setUsername(e.target.value)
                    e.target.value === 0
                        ? () => setErrorMessageForUsername('名前を入力してください')
                        : () => setErrorMessageForUsername('')
                }
```

canSubmitに書くとなぜ`Too many re-renders`になるのかは、ちょっと複雑になるので口頭で説明しま

2022-06-11 09:58 UTC, sayanok commented on front/src/components/SettingsProfile.js
> +    }
めも
・カスタムフックにする？
→いくつかエラー発生してるので相談したい

・useNavigateだけメソッド外にする？

2022-06-12 09:03 UTC, merged