Add reply button
sayanok/zetter pull request #26
Opened 2022-07-15 02:32 UTC by sayanok

2022-07-17 03:04 UTC, sayanok commented
componentの方針を変更
![iOS の画像](https://user-images.githubusercontent.com/48172627/179382065-84cb5e73-81b5-4deb-90b7-24bdfc0171de.jpg)

2022-07-21 03:01 UTC, sayanok reviewed
TweetDetail.tsx

2022-07-21 03:01 UTC, sayanok commented on front/src/TweetDetail.tsx
> +
こっちを取得する
![getTweet](https://user-images.githubusercontent.com/48172627/180120414-9f868d0e-beed-47dd-8286-ad4969e5604c.png)

2022-07-21 03:01 UTC, sayanok commented on front/src/TweetDetail.tsx
> +    }
こっちを取得する
![getReplys](https://user-images.githubusercontent.com/48172627/180120529-7c6498be-94ec-4142-b65a-2678d5c3a53b.png)

2022-07-21 03:01 UTC, sayanok commented on front/src/TweetDetail.tsx
> +    }
返信元ツイートとリプライツイート両方を取得してセットする
これでいいねとかリプライの件数が反映される

2022-07-21 03:01 UTC, sayanok commented on front/src/TweetDetail.tsx
> +    }
こっちのいいね
![getTweet](https://user-images.githubusercontent.com/48172627/180120676-0537774f-ed6b-4023-8bc9-fff073605410.png)

2022-07-21 03:01 UTC, sayanok commented on front/src/TweetDetail.tsx
> +        }
こっちのいいね
![getReplys](https://user-images.githubusercontent.com/48172627/180120739-570df018-d4f9-4a56-bb67-89c40c740676.png)

2022-07-21 03:51 UTC, sayanok commented on front/src/TweetTree.tsx
> +    }
何箇所かで出てくるのでuseCallApiみたいに共通化した方が良い？
実験してみたところ、苦戦
苦戦した箇所は`setReplyTweetsList`といった、配列をセットするメソッドを引数として渡すこと

2022-07-21 03:51 UTC, sayanok commented on front/src/TweetTree.tsx
> +const TweetTree: React.FC<TweetTreeProps> = (props) => {
結構TweetDetailComponentに似てるけど、TweetDetailComponentは親子関係になれないComponentだから仕方ないと認識している

2022-08-16 23:14 UTC, bigen1925 requested changes

2022-08-16 23:14 UTC, bigen1925 commented on api/controllers/zetter.js
> +    const sortedTweets = tweets.sort(function (a, b) {
`<array>.sort()`メソッドは返り値としてソート後の配列を返すんだけど、メソッド自体は破壊的メソッドなので、再定義せずに使ったほうがいいかも

2022-08-16 23:14 UTC, bigen1925 commented on api/controllers/zetter.js
>          }
```suggestion
        return b.createdAt - a.createdAt
```
でも良い

2022-08-16 23:14 UTC, bigen1925 commented on api/controllers/zetter.js
> +    }
```suggestion
    tweet.isFavorite = favoriteTweetIds.includes(tweet.id);
```
だけでよい

2022-08-16 23:14 UTC, bigen1925 commented on api/controllers/zetter.js
> +function addInformationToTweet(tweetList, req) {
25-39行目もうまくまとめたいね

2022-08-16 23:14 UTC, bigen1925 commented on front/src/ReplyButton.tsx
> +            >
```suggestion
            <Modal
                open={open}
                onClose={(e: Event) => {
                    e.preventDefault();
                    handleClose();
                }}
                aria-labelledby="modal-modal-title"
                aria-describedby="modal-modal-description"
                sx={{ backgroundColor: "#ffffff00" }}
            >
```
って書くとCSSはいらないよ

https://mui.com/system/getting-started/the-sx-prop/

2022-08-16 23:14 UTC, bigen1925 commented on front/src/ReplyButton.tsx
> +            {props.tweet.numberOfReply}
関連するコードはできるだけ近くに書いたほうがよい（専門的には「凝集性が高い」と言う）、というのが読みやすいコードの原則なので、これはModalより上に書いたほうが読みやすいと思う

```jsx
<>
  <Buttton ...> ... </Button>
  {props.tweet.numberOfReply}

  {/* リプライモーダル */}
  <Modal ...>
    ...
  </Modal>

</>
```
みたいな感じ？

2022-08-16 23:14 UTC, bigen1925 commented on front/src/SingleTweet.tsx
> +            <Link to={'/tweet/' + props.tweet.id}>
```suggestion
            <Link to={`/tweet/${props.tweet.id}`>
```
こういう書き方もできる
これは完全に好み

2022-08-16 23:14 UTC, bigen1925 commented on front/src/SingleTweet.tsx
> +                        <React.Fragment>
```suggestion
                        <>
```

他のところとあわせてこれでいいんじゃないかな

2022-08-16 23:14 UTC, bigen1925 commented on front/src/SingleTweet.tsx
> +                    }
```suggestion
                    primary={
                        <>
                            {props.tweet.user.username + '・' + formatDate(props.tweet.createdAt)}
                        </>
                    }
```
これでよい

2022-08-16 23:14 UTC, bigen1925 commented on front/src/SingleTweet.tsx
> +                        <React.Fragment>
```suggestion
                        <>
```

2022-08-16 23:14 UTC, bigen1925 commented on front/src/TweetDetail.tsx
> +        }
```suggestion

            // favの切り替え
            callApi('http://localhost:5000/api/zetter', {
                method: 'PATCH',
                body: JSON.stringify({ tweet: tweet, order: tweet.isFavorite ? 'delete' : 'add' }),
            })?.then((data) => {
                setTweet(data);
            });
```
とかでもシンプルかも

2022-08-16 23:14 UTC, bigen1925 commented on front/src/TweetDetail.tsx
> +            });
```suggestion
            })?.then((newReply) => {
                let newReplies = replyTweetsList.map(reply =>  {
                    if (newReply.id === reply.id) {
                        return newReply;
                    } else {
                        return reply;
                    }
                });
                setReplyTweetsList(result);
            });
```
1. 名前がdataとかresultだと何を指してるかわかりにくくて読みにくかった　具体的な名前のほうが良いと思う
2. 他のところではアロー関数使ってるので、ここも合わせていこう

2022-08-16 23:14 UTC, bigen1925 commented on front/src/TweetForm.tsx
> +    );
ここはstateじゃなくて良い（じゃないほうが良い）
```suggestion
    cons content = props.replySourceTweet ? '@' + props.replySourceTweet.user.username : '';
```
たんにこれでok

2022-08-16 23:14 UTC, bigen1925 commented on front/src/TweetForm.tsx
> +    const [placeholder, setPlaceholder] = useState<string>('今然ぴどうしてる？');
ここもstateを使う必要はない （使わないほうが良い）

```suggestion
    const placeholder = props.replySourceTweet ? '返信をツイートする' : '今然ぴどうしてる？'
```

2022-08-16 23:14 UTC, bigen1925 commented on front/src/TweetTree.tsx
> +    }
共通化したほうが良いね

2022-08-16 23:14 UTC, bigen1925 commented on front/src/TweetTree.tsx
> +    }
インターフェース的には
```ts
async function callUpdateFavoriteApi(tweet: TweetType): Promise<TweetType | undefined>: {
  ...
}
```

```ts
function updateReplyFavoriteState(reply: TweetType): void {
  callUpdateFavoriteApi(reply)?.then(newReply => {
    let newReplies = replyTweetsList.map((reply: TweetType): TweetType {
      if (newReply.id === reply.id) {
        return newReply;
      } else {
        return reply;
      }
    });

    setReplyTweetsList(result);
  })
}
```

みたいになるんちゃうかな

2022-08-16 23:14 UTC, bigen1925 commented on front/src/TweetTree.tsx
> +const TweetTree: React.FC<TweetTreeProps> = (props) => {
よくわかんないけどTweetTree使ってください

2022-09-05 12:47 UTC, sayanok commented on front/src/TweetTree.tsx
> +const TweetTree: React.FC<TweetTreeProps> = (props) => {
自分のコメント内容よくわからんし多分良さそうなのでいったんこのままで良いということになった(?)

2022-09-05 12:49 UTC, merged